# 第一讲（2024/2/22）
*作者：李惟简*

## 经济学思想基础

经济学是社会科学中研究人类理性的边际决策的学科。理性不仅是假设，更是经济学研究的前提，非理性的决策归于心理学的研究范畴。边际指理性人针对增量的变化开展决策，而非存量。经济学的哲学基础是客观唯心主义，研究者相信均衡的潜在力量影响人类决策，进而推动经济系统的运行。

### 经济系统

经济学构建的是由变量和等式描述的均衡系统。

经济学研究的变量从变化来源看分为**内生变量**和**外生变量**。**内生变量是系统需要研究的变量，外生变量是给定系统的条件。**

**例：** 在供需模型中，均衡数量和价格是内生变量，其他变量是外生的。

经济学研究的变量从变化属性看分为**流量**和**存量**。**流量是一段时间内的经济系统特征的变化量，存量是一个时点上经济系统的状态**。

**例：**失业率和失业人数是存量，新增失业人口是流量。

经济学研究的等式系统来自优化问题。经济决策主体基于给定的约束条件作出优化决策，决策结果和约束条件呈现为等式系统。经济学的等式系统分为均衡式和恒等式。均衡式来自经济系统参与者的决策，恒等式是经济叙述的等价表述。

**例：** 供需均衡是均衡式，净出口等于出口减进口是恒等式。

### 分析方法

经济学的分析方法包括**实证分析**和**规范分析**。**实证分析研究经济系统内生变量与外生变量的均衡关系，规范分析研究对内生变量表现的价值取向。**本门课程研究的每部分内容均是实证分析，一般来说，规范分析应该作为实证分析的前提条件，在确认价值取向后只应涉及实证分析。

**例：** 代议制民主是否正义是规范分析，如何提高代议制民主效率是实证分析。

### 研究结论

经济学的研究结论呈现为相关关系与因果关系。相关关系仅由统计观察即可得到，因果关系应该来自均衡机制的分析。

**例：** 气温升高导致游泳人数上升是因果关系，冷饮消费量上升和游泳人数上升同向变动是相关关系。

## 宏观经济学研究框架

**宏观经济学**是研究经济系统总量波动和增长的学科。

宏观经济学是经济科学的重要领域，经济学的一切思想和方法均在宏观经济学中适用。经济学的基础思想是微观经济学的优化、供需与边际理论，宏观系统亦由微观个体聚合而成。但是微观变量加总至宏观并非简单的线性加权累加，这是尤需注意的。

**例：**微观供给量随物价上升。但物价不影响宏观长期均衡的总供给量。

### 古典主义：长期均衡

古典主义经济学研究总量在经济系统长期达到的均衡状态。长期均衡由价格引导下的无套利机制实现，即市场上的供给方和需求方根据价格做出反应，调整供给量和需求量，使总量达到均衡。因此**长期的定义是所有变量都能自由调整需要的最短时间。**长期物价反映的是商品交换的比例关系，因此物价总水平不影响实际变量。实际变量由生产能力的物理约束决定。

### 古典主义：超长期增长

古典主义视角下经济系统的生产能力在超长期逐渐提高，从而带来实际变量的系统性变化。这一系统性变化成为经济增长，是宏观研究的重要领域。

### 凯恩斯主义：短期波动

凯恩斯主义关注短期经济的波动，**短期的定义是部分变量存在粘性，不能自由调节的时期。**部分变量的粘性导致市场不能通过均衡机制的灵活调节保持均衡状态，出现对均衡的偏离。从短期向长期变化的过程是粘性变量的粘性逐渐消失的过程，伴随着均衡的恢复。均衡的偏离和恢复称为经济波动，是宏观研究的另一个重要领域

## GDP：国内生产总值

现代文明认为发展的最终目标是提高人民的生活水平。人民的生活水平体现在运用生产所得带来的幸福，即经济效用。衡量一个经济体给其成员带来总经济效用的研究叫做国民财富核算，该研究主要使用**国内生产总值**来核算国民财富。

因此，国内生产总值的定义和国民财富总量息息相关。**国内生产总值的定义是，一定时期内一国或一地区内新增生产的最终生产品以市场价值计价的总量。**关于该定义需要注意以下方面：

- **一定时期：** GDP是流量概念。
- **一国或一地区内：** 地理概念。**区别于GNP，其乃一国国民产量之总和。**
- **新增生产：** 物质的增加值才形成生活水平的提升。
- **最终产品：** 未完成的商品计入存货，完成时应从存货消去。
- **市场价值：** 市场价值才能体现效用水平，GDP不适用于计划经济。

### GDP的测算

经济系统的每一个组成成员，同时既是生产者也是消费者。一单位商品生产出来后，必是流向了消费者，形成了消费者的支出。该商品的生产者获得了收入，可以支出到其他商品中。由上述逻辑可以得到三种等价的GDP核算方法：

- **生产法：** 生产出的增加值总额。是中国最常用的核算法，脱胎于计划经济的计划生产管理，我国的增值税制度亦基于此。
- **支出法：** 各部门支出总额。是西方常用的核算法，适用于分解经济增长来源。
- **收入法：** 各部门收入总额。统计粗疏，常用于研究分配。

### GDP的分解

**支出法视角下的GDP可以分解为消费、投资、政府购买和净出口四部分。** 体现为以下**均衡式**（该式永远成立）：

\[Y = C + I + G + NX\]

- **消费(C):** 包括非耐久品、耐久品和服务。其中**耐久品房产属于投资，购买二手商品不计入消费**。
- **投资(I):** 包括房地产、基建、固定资产投资和存货。其中**房租和利润不属于生产**，存货变动较大，为研究者所重视。
- **政府购买(G):** **不包括转移支付。**
- **净出口(NX):** 减去进口是因为该部分已被包含在消费。



